/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoImportacao;

import ProjetoImportacao.Model.MovimentoEstoque;
import ProjetoImportacao.Model.Repositorio.MovimentoEstoqueRepositorio;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VanessaCristine
 */
public class FrmHistoricoMovimentacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRelatorio
     */
    public FrmHistoricoMovimentacao() {
        initComponents();
        CarregarGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPagina = new javax.swing.JLabel();
        PProduto = new javax.swing.JPanel();
        Estoque = new javax.swing.JTabbedPane();
        BR = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CHL = new javax.swing.JScrollPane();
        Relatorio = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setClosable(true);

        lblTituloPagina.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPagina.setForeground(new java.awt.Color(102, 102, 255));
        lblTituloPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetoImportacao/Relatorio.jpg"))); // NOI18N
        lblTituloPagina.setToolTipText("");

        PProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimentação"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Mov.", "Produto", "Qte", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BR.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        Estoque.addTab("BR", BR);

        Relatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Mov.", "Produto", "Qte", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CHL.setViewportView(Relatorio);
        if (Relatorio.getColumnModel().getColumnCount() > 0) {
            Relatorio.getColumnModel().getColumn(0).setResizable(false);
            Relatorio.getColumnModel().getColumn(1).setResizable(false);
            Relatorio.getColumnModel().getColumn(2).setResizable(false);
            Relatorio.getColumnModel().getColumn(3).setResizable(false);
        }

        Estoque.addTab("CHL", CHL);

        javax.swing.GroupLayout PProdutoLayout = new javax.swing.GroupLayout(PProduto);
        PProduto.setLayout(PProdutoLayout);
        PProdutoLayout.setHorizontalGroup(
            PProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );
        PProdutoLayout.setVerticalGroup(
            PProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            // TODO add your handling code here:
       CarregarGrid();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    public void CarregarGrid()
    {
     MovimentoEstoqueRepositorio rep = new MovimentoEstoqueRepositorio();
        List<MovimentoEstoque> movimentos = rep.Listar(null);
        
        List<MovimentoEstoque> movimentosBr = movimentos.stream().filter(p -> "br".toUpperCase().equals(p.getPais().toUpperCase()) ).collect(Collectors.toList());
        
        List<MovimentoEstoque> movimentosCh = movimentos.stream().filter(p -> "chl".toUpperCase().equals(p.getPais().toUpperCase()) ).collect(Collectors.toList());
        
        DefaultTableModel userTableModel = new DefaultTableModel( new Object[]{"Tipo Mov.","Produto", "Qte", "Data" }, 0 );
        
        for (MovimentoEstoque m : movimentosBr) {
            Object[] o = new Object[4];
            o[0] = m.getTipoMovimentacao();
            o[1] = m.getEstoque().getProduto().getNome();
            o[2] = m.getQuantidade();
            o[3] = m.getData();
            
            userTableModel.addRow(o);
          }
        jTable1.setModel(userTableModel);
        
        userTableModel = new DefaultTableModel( new Object[]{ "Tipo Mov.","Produto", "Qte", "Data" }, 0 );
        
        for (MovimentoEstoque m : movimentosCh) {
            Object[] o = new Object[4];
            o[0] = m.getTipoMovimentacao();
            o[1] = m.getEstoque().getProduto().getNome();
            o[2] = m.getQuantidade();
            o[3] = m.getData();
            
            userTableModel.addRow(o);
          }
        Relatorio.setModel(userTableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BR;
    private javax.swing.JScrollPane CHL;
    private javax.swing.JTabbedPane Estoque;
    private javax.swing.JPanel PProduto;
    private javax.swing.JTable Relatorio;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTituloPagina;
    // End of variables declaration//GEN-END:variables
}
