/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoImportacao;

import ProjetoImportacao.Model.Importacao;
import ProjetoImportacao.Model.Repositorio.ImportacaoRepositorio;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VanessaCristine
 */
public class FrmRastreamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRastreamento
     */
    public FrmRastreamento() {
        initComponents();
        CarregarGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPagina = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        CHL = new javax.swing.JScrollPane();
        Relatorio = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);

        lblTituloPagina.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPagina.setForeground(new java.awt.Color(102, 102, 255));
        lblTituloPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetoImportacao/Rastreamento.jpg"))); // NOI18N
        lblTituloPagina.setToolTipText("");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        Relatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.Barras", "Produto", "Quantidade", "Data Envio", "Dt Receb.", "Status"
            }
        ));
        CHL.setViewportView(Relatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addComponent(CHL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloPagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CHL, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        CarregarGrid();
    }//GEN-LAST:event_btnAtualizarActionPerformed

 public void CarregarGrid()
    {
     ImportacaoRepositorio rep = new ImportacaoRepositorio();
     List<Importacao> movimentos = rep.Listar(null);
        
        DefaultTableModel userTableModel = new DefaultTableModel( new Object[]{ "Cód.Barras", "Produto", "Quantidade", "Data Envio", "Dt Receb.", "Status" }, 0 );
        
        for (Importacao m : movimentos) {
            Object[] o = new Object[6];
            o[0] = m.getCodigoBarras();
            o[1] = m.getProduto().getNome();
            o[2] = m.getQuantidade();
            o[3] = m.getDataEnvio();
            o[4] = m.getDataRecebimento();
            o[5] = m.getStatus();
            
            userTableModel.addRow(o);
          }
        Relatorio.setModel(userTableModel);
       
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CHL;
    private javax.swing.JTable Relatorio;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel lblTituloPagina;
    // End of variables declaration//GEN-END:variables
}
